import type { ImgHTMLAttributes } from 'react';

interface CharacterArtProps
  extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'width' | 'height'> {
  name: string;
  widths: readonly number[];
  width: number;
  height: number;
}

/**
 * Responsive character artwork generated by `npm run characters`.
 * Width and height are always explicit so transparent art never shifts layout.
 */
const CharacterArt: React.FC<CharacterArtProps> = ({
  name,
  widths,
  width,
  height,
  alt,
  sizes,
  ...props
}) => {
  const largest = widths[widths.length - 1];
  const srcSet = widths
    .map((candidate) => `/characters/character-${name}-${candidate}.webp ${candidate}w`)
    .join(', ');

  return (
    <img
      src={`/characters/character-${name}-${largest}.webp`}
      srcSet={srcSet}
      sizes={sizes}
      width={width}
      height={height}
      alt={alt}
      decoding="async"
      {...props}
    />
  );
};

export default CharacterArt;
